### ISSUE TITLE
Add support for adding ghcup release channel (-> GHC pre-releases)

### ISSUE THREAD

**Issue by robx** [haskell/actions#108]
(Reference: #107.)

`ghcup` supports installing non-standard GHC releases via so-called "release channels": https://www.haskell.org/ghcup/guide/#pre-release-channels

I'd like to propose an input to this action for adding an extra release channel. I.e.:

```
inputs:
  ...
  ghcup-release-channel:
    required: false
    description: "A release channel to add to ghcup via `ghcup add-release-channel`."
```

If set, this would mean that the action calls

```
ghcup add-release-channel ${ghcup-release-channel}
```

before the call to `ghcup install`.

This would add support for GHC pre-releases by allowing users to add the release channel managed at https://github.com/haskell/ghcup-metadata/blob/master/ghcup-prereleases-0.0.7.yaml.

(Ideally, the GHC HEAD support (#93) could be folded into this too at some point -- the nice thing about the ghcup metadata is that it takes care of that deb9/deb10/deb11 confusion.)
