### ISSUE TITLE
Neutral in the choice of build tools

### ISSUE THREAD

**Issue by L-TChen** [haskell/actions#12]
It does not seem necessary to set up cabal whenever this action is used, if the intended build tool is stack. Setting up `cabal` is currently costly (about 30s), since the action downloads the version 3.2 of cabal instead of using the one 3.4 provided by runner. 

Also, it will be nice to have an option for stack to choose the system GHC by default.

**Comment by vrom911** [comment]
> Also, it will be nice to have an option for stack to choose the system GHC by default.

I think this is the question to Stack, but it already has this option. You can use:

```shell
stack ... --system-ghc
```

From help:

```
  --[no-]system-ghc        Enable/disable using the system installed GHC (on the
                           PATH) if it is available and its version matches.
                           Disabled by default.
```

Regarding the initial question, I am not sure if this is what you mean, but in the action, there is already this option:

```
  stack-no-global:
    required: false
    description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally'
```

**Comment by L-TChen** [comment]
> > Also, it will be nice to have an option for stack to choose the system GHC by default.
> 
> I think this is the question to Stack, but it already has this option. You can use:
> 
> ```shell
> stack ... --system-ghc
> ```
> 
> From help:
> 
> ```
>   --[no-]system-ghc        Enable/disable using the system installed GHC (on the
>                            PATH) if it is available and its version matches.
>                            Disabled by default.
> ```
Yes, I know it can be set via this option from CLI or from the local/global configuration. Yet, it will just make life easier to set up a global stack configuration altogether via this action directly.

> Regarding the initial question, I am not sure if this is what you mean, but in the action, there is already this option:
> 
> ```
>   stack-no-global:
>     required: false
>     description: 'If specified, enable-stack must be set. Prevents installing GHC and Cabal globally'
> ```
Hum, it looks so. The description is confusing to me, since it is not clear what would happen if I have `stack-no-global` true but `ghc-version` specified.

**Comment by L-TChen** [comment]
Right, `stack-no-global` prevents installing GHC and Cabal, but there is no way to have GHC enabled but Cabal disabled.

https://github.com/haskell/actions/blob/0386b0add060b8d9c78d6eb779e49c6f523c0d4e/setup/src/opts.ts#L96-L106

It will be really great if there are options
- `global-ghc` which defaults to `true`
- `enable-cabal` which defaults to `true` and requires `global-ghc` to be true

so that these options will not break existing workflows but add enough flexibility.

**Comment by jared-w** [comment]
This has actually come up before. At the time, the runner was correctly synced with the latest version of cabal, so there was no runtime hit to install it and what I did was just prevented cabal-update from running if stack was enabled, which wasn't necessarily the most correct solution, but it was the most minimal change.

I would like to improve the situation, though; I've always intended for this action to be neutral in build tool choice.

Splitting out stack-no-global into its two separate options and leaving it as the shortcut to enable both makes sense to me. How about this addition to action.yml?

```yaml
  enable-cabal:
    required: false
    description: 'If specified, will install the specified version of cabal-install globally'
  enable-ghc:
    required: false
    description: 'If specified, will install the specified version of GHC globally'
    default: 'true'
  stack-use-system-ghc:
    required: false
    description: 'If specified, enable-ghc must be set. Will configure stack to use the globally installed GHC.'
```

`stack-use-system-ghc` would append the setting `system-ghc: true` to `/etc/stack/config.yaml`. Would that work?
