### ISSUE TITLE
Output "stack-root " on Windows is not working

### ISSUE THREAD

**Issue by Sorokin-Anton** [haskell/actions#120]
## How to reproduce:
Try to run CI.yml with GitHub runner
```
jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        stack: ["2.7.5"]
        ghc: ["9.0.2"]
        include:
          - ghc: "9.0.2"
            stackyaml: stack.yaml
    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.0.1
      id: setup-haskell-stack
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v3
      name: Cache stack root
      with:
        path: ${{ steps.setup-haskell-stack.outputs.stack-root }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack
    ...
```

### What should happen:
`${{ steps.setup-haskell-stack.outputs.stack-root }}` is replaced by stack root created in setup

### What happens:
Build fails with `Error: Input required and not supplied: path`

## Additional info:
If I try to run `echo "${{ steps.setup-haskell-stack.outputs.stack-root }}"`, it prints empty string
