### ISSUE TITLE
Incorporate get-tested as an action

### ISSUE THREAD

**Issue by Kleidukos** [haskell/actions#189]
https://github.com/Kleidukos/get-tested could be provided in a more ergonomic to encourage package maintainers to declare supported compiler versions in their cabal files.

cc @hazelweakly

**Comment by Kleidukos** [comment]
@michaelpj I believe this is relevant to your experiment on the HLS repo

**Comment by michaelpj** [comment]
HLS has many packages so putting all the information in the cabal files would be a lot of duplication, which defeats the point a bit. What I'm trying to do in that PR is reduce the duplication that we already have.

I'm sure it's a different story for single-package repos!

**Comment by Kleidukos** [comment]
Thanks for the clarification! :)

**Comment by Kleidukos** [comment]
> Could you spell out your intent, i.e., what you mean by "could be provided in a more ergonomic way"?

Okay so at the moment, its usage looks like this:

```yaml
jobs:                                                                                                                   
  generateMatrix:                                                                                                       
    name: "Generate matrix from cabal"                                                                                  
    runs-on: ubuntu-latest                                                                                              
    outputs:                                                                                                            
      matrix: ${{ steps.set-matrix.outputs.matrix }}                                                                    
    steps:                                                                                                              
      - name: Checkout base repo                                                                                        
        uses: actions/checkout@v2                                                                                       
      - name: Extract the tested GHC versions                                                                           
        id: set-matrix                                                                                                  
        run: |                                                                                                          
          wget https://github.com/Kleidukos/get-tested/releases/download/v0.1.3.0/get-tested-0.1.3.0-linux-amd64 -O get-tested
          chmod +x get-tested                                                                                           
          ./get-tested --ubuntu --macos text-display.cabal >> $GITHUB_OUTPUT
```

and I'd like to provide an action so that it may be used as:

```yaml
jobs:
  generateMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
      - name: Extract the tested GHC versions
        id: set-matrix
        uses: actions/haskell/test-matrix # proper GH Action
```
