### ISSUE TITLE
Add `cache` action?

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/actions#216]
I'm very illiterate in caching of haskell builds in GHA, so take with a grain of salt. Not small part of it is ugly and bulky incantations people usually use there. E.g cabal's workflow:

```
      - if: ${{ runner.os != 'Windows' }}
        uses: actions/cache@v3
        with:
          # validate.sh uses a special build dir
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-*
          key: ${{ runner.os }}-${{ matrix.ghc }}-20220419-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-20220419-
```

Julia (the language) had very nice cache action that makes the task a one liner and hides complexity. Could we have the same? https://github.com/julia-actions/cache
