### ISSUE TITLE
Minimal `stack`-native example

### ISSUE THREAD

**Issue by ocramz** [haskell/actions#266]
I've found the following to be an intuitive setup: no new flags are needed, no need to tweak with system GHC installations, etc.

Perhaps consider adding it to the list of examples?

```yaml
jobs:
  build:
    name: stackage ${{ matrix.stack-resolver }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        stack-resolver: ['nightly-2023-06-17', 'lts-20.24']
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Setup compiler, build and test
        run: |
          stack build --resolver ${{ matrix.stack-resolver }}
          stack test
```
