### ISSUE TITLE
Caching dist-newstyle still rebuilds project tests every time

### ISSUE THREAD

**Issue by raehik** [haskell/actions#41]
I'm trying to cache `~/.cabal/store` and `dist-newstyle` for my Cabal builds using this action. With that, I expect that if I make a non-code change, Cabal shouldn't have to rebuild anything. But no matter what I try, Cabal will always rebuild the project tests.

One message in the log sticks in my mind:

  >  ./<project>.cabal has been changed. Re-configuring with most recently used options. If this fails, please run configure manually.

But I don't know what this means: the `*.cabal` file isn't edited at all on CI. Also, the library build succeeds just fine, that message only shows on tests.

My tests are at raehik/reprinter [(example problematic run workflow)](https://github.com/raehik/reprinter/actions/runs/599557658/workflow#L37). Larger project building at raehik/fortran-src [(example problematic run log)](https://github.com/raehik/fortran-src/runs/1979454377?check_suite_focus=true#step:7:9).

Similar commands run locally don't have this behaviour. I managed to sort most of my issues (Cabal will rebuild the project too if unrelated flags aren't kept the same), but I'd like to know why this occurs. Hope this is relevant, I realise it's a bit of a StackOverflow question -- let me know if I should take it elsewhere.

**Comment by tfausak** [comment]
It's likely that the rebuild is caused by GHC, not Cabal. The way that GHC determines if it needs to rebuild a file is to compare the source file's timestamp to the compiled file's timestamp. If the source file is newer, it rebuilds. Typically with local workflows this works fine. Unfortunately on CI the first thing that happens is usually cloning the repository, which sets all the source file timestamps to "now". Since all the source files are apparently newer, everything gets rebuilt. 

You could solve this problem by manually tracking the timestamps for all your source files. That should work even though it will be a little tedious. 

There's an upstream issue against GHC for this behavior: https://gitlab.haskell.org/ghc/ghc/-/issues/16495

**Comment by raehik** [comment]
Thanks very much @tfausak ! I was especially confused because Stack appeared to work fine/as expected. That issue explains everything, I see you worked on solving it last year.

And your suggestion works perfectly. Putting this snippet at the start of a job:

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
- name: Set all tracked file modification times to the time of their last commit
  run: |
    rev=HEAD
    for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
        touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
    done
```

appears to get me the caching behaviour I was hoping for. Thanks again for your help. If you think any of this is useful/common enough to add as a note in this repo, I'd gladly do that. I'll close this issue for now.
