### ISSUE TITLE
Cabal version 3.2 is requested, and yet cabal 3.4 is installed

### ISSUE THREAD

**Issue by mrkkrp** [haskell/actions#45]
I'm quite confused. Here is a fragment of my workflow:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.6.5", "8.8.4", "8.10.3"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: haskell/actions/setup@v1.1.5
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal --version
```

I request Cabal 3.2 and indeed in the log it looks like that's what is installed:

```
Installing cabal version 3.2.0.0
  /opt/hostedtoolcache/ghcup/0.1.12/x64/ghcup set cabal 3.2.0.0
  [ Warn  ] New GHCup version available: 0.1.13. To upgrade, run 'ghcup upgrade'
  [ Error ] NotInstalled Cabal "3.2.0.0"
  Found cabal 3.2.0.0 in cache at path /home/runner/.ghcup/bin. Setup successful.
```

However, when `cabal --version` is called immediately after the `setup` action, it says:

```
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
```

[See here](https://github.com/mmark-md/mmark/pull/77/checks?check_run_id=2046957420)

What I expect is that if I specify 3.2, then I should get that version of cabal.
