### ISSUE TITLE
Matchers-only option

### ISSUE THREAD

**Issue by parsonsmatt** [haskell/actions#71]
We use `nix` in CI to provide GHC and all relevant tools, but we also want the error matchers.

As a work around, we've got this config in our GitHub Actions file:

```yaml
        # we use the Haskell setup action because it integrates error matching.
        # we don't use it to bring in GHC or any other Haskell tooling - that
        # is all provided by Nix. 
      - uses: haskell/actions/setup@v1
        # This little stanza is what we need to prevent installing a redundant
        # GHC. It does install a redundant stack, but that's a much smaller
        # problem.
        with:
          enable-stack: true
          stack-no-global: true
```

This takes ~0s according to GitHub, which is great.

However, it'd be *ideal* to either have a `ghc-matchers` GitHub action or a `matchers-only` option.
