### ISSUE TITLE
Does not use apt-get installed GHCs

### ISSUE THREAD

**Issue by sol** [haskell/actions#80]
Here is a repro:

```yaml
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          cabal-version: '3.4'
          ghc-version: '7.4.1'
      - run: ghc --version
```

- installs 7.4.1: https://github.com/sol/haskell-setup-action-bug/runs/4094359642?check_suite_focus=true#step:3:88
- but uses 9.2.1: https://github.com/sol/haskell-setup-action-bug/runs/4094359642?check_suite_focus=true#step:4:4
